<?xml version="1.0" encoding="utf-8"?><Database Name="track-dev" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=18.223.218.151,49170,49170;Initial Catalog=track-dev;Persist Security Info=True;User ID=dev" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="track_devConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dataset" Member="Datasets">
    <Type Name="Dataset">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Series" Member="Series">
    <Type Name="Series">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DatasetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="Char(6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Record" Member="Records">
    <Type Name="Record">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DatasetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Property" Member="Properties">
    <Type Name="Property">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecordId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SeriesId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SeriesType" Member="SeriesTypes">
    <Type Name="SeriesType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.GetDatasets" Method="GetDatasets">
    <ElementType Name="GetDatasetsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateSeries" Method="UpdateSeries">
    <Parameter Name="SeriesId" Parameter="seriesId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Label" Parameter="label" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="Char(6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateDataset" Method="UpdateDataset">
    <Parameter Name="DatasetId" Parameter="datasetId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Label" Parameter="label" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetSeriesTypes" Method="GetSeriesTypes">
    <ElementType Name="GetSeriesTypesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSeries" Method="GetSeries">
    <Parameter Name="DatasetId" Parameter="datasetId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSeriesResult">
      <Column Name="SeriesId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SeriesType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRecordsNew" Method="GetRecordsNew">
    <Parameter Name="DatasetId" Parameter="datasetId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRecordsNewResult">
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Properties" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRecordsFinal" Method="GetRecordsFinal">
    <Parameter Name="DatasetId" Parameter="datasetId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRecordsFinalResult">
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Properties" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRecordsBest" Method="GetRecordsBest">
    <Parameter Name="DatasetId" Parameter="datasetId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRecordsBestResult">
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Properties" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRecords" Method="GetRecords">
    <Parameter Name="DatasetId" Parameter="datasetId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRecordsResult">
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Properties" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDatasets" Method="GetDatasets1">
    <ElementType Name="GetDatasetsResult1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDataset" Method="GetDataset">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetDatasetResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CreateRecord" Method="CreateRecord">
    <Parameter Name="DatasetId" Parameter="datasetId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateTime" Parameter="dateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Note" Parameter="note" Type="System.String" DbType="VarChar(200)" />
    <ElementType Name="CreateRecordResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CreateDataset" Method="CreateDataset">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Label" Parameter="label" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CreateDatasetResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ArchiveDataset" Method="ArchiveDataset">
    <Parameter Name="DatasetId" Parameter="datasetId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Archive" Parameter="archive" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddSeries" Method="AddSeries">
    <Parameter Name="DatasetId" Parameter="datasetId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TypeId" Parameter="typeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Label" Parameter="label" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Unit" Parameter="unit" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddProperty" Method="AddProperty">
    <Parameter Name="RecordId" Parameter="recordId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Label" Parameter="label" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>